---
- hosts: build
  remote_user: "{{ host_build_user }}"
  roles:
      - role: build_and_save_container
        dockerfile_dir: '../'
        extra_rsync_opts: '--filter="dir-merge /.rsync-filter-workaround",--filter="- .rsync-filter-workaround",--filter="dir-merge /.rsync-filter-incoming",--filter="- .rsync-filter-incoming"'
        image_file_name: 'incoming'
        image_name: 'lars.tiede/incoming'
        image_tag: 'latest'
        remove_image_from_host: True
      - role: build_and_save_container
        dockerfile_dir: '../examples/'
        extra_rsync_opts: '--filter="dir-merge /.rsync-filter-examples",--filter="- .rsync-filter-examples"'
        image_file_name: 'incoming_examples'
        image_name: 'lars.tiede/incoming_examples'
        image_tag: 'latest'
        remove_image_from_host: True
      - role: build_and_save_container
        dockerfile_dir: '../example_webserver/'
        image_file_name: 'incoming_example_webserver'
        image_name: 'lars.tiede/incoming_example_webserver'
        image_tag: 'latest'
        remove_image_from_host: True
  vars:
      - image_storage_dir: docker_images

- hosts: test
  remote_user: root
  roles:
      - role: install_container_from_archive
        image_file_name: 'incoming'
      - role: install_container_from_archive
        image_file_name: 'incoming_examples'
      - role: install_container_from_archive
        image_file_name: 'incoming_example_webserver'
      - role: has_private_keys
      - role: incoming_and_examples_on_one_host
        host_fqdn: ''
        # pass in a non-empty value if you want to explicitly set the fqdn.
        # Otherwise, ansible_fqdn will be used. (Best set this as a host
        # variable)
        nginx_server_port: 80
        nginx_ssl_server_port: 443
        example_port: 4002
        # 4001 is 'example 1'
        # 4002 is 'example 2'
        incoming_port_maps: "20000:22"
        incoming_examples_port_maps: "20002:22"
        # outcomment the above defs to not expose any ports. Syntax is the one
        # used in the ansible docker module.
  vars:
      - image_storage_dir: docker_images
