---
- hosts: build
  remote_user: "{{ host_build_user }}"
  roles:
      - role: build_and_save_container
        dockerfile_dir: '../'
        extra_rsync_opts: '--filter="dir-merge /.rsync-filter-incoming",--filter="- .rsync-filter-incoming"'
        image_file_name: 'incoming'
        image_name: 'lars.tiede/incoming'
        image_tag: 'latest'
        remove_image_from_host: False
      - role: build_and_save_container
        dockerfile_dir: '../examples/'
        extra_rsync_opts: '--filter="dir-merge /.rsync-filter-examples",--filter="- .rsync-filter-examples"'
        image_file_name: 'incoming_examples'
        image_name: 'lars.tiede/incoming_examples'
        image_tag: 'latest'
        remove_image_from_host: False
      - role: build_and_save_container
        dockerfile_dir: '../example_webserver/'
        image_file_name: 'incoming_example_webserver'
        image_name: 'lars.tiede/incoming_example_webserver'
        image_tag: 'latest'
        remove_image_from_host: False
  vars:
      - image_storage_dir: docker_images

- hosts: test
  remote_user: root
  roles:
      - role: install_container_from_archive
        image_file_name: 'incoming'
      - role: install_container_from_archive
        image_file_name: 'incoming_examples'
      - role: install_container_from_archive
        image_file_name: 'incoming_example_webserver'
      - role: has_private_keys
      - role: incoming_and_examples_on_one_host
        nginx_server_port: 80
        nginx_ssl_server_port: 443
        example_port: 4002
        # 4002 is 'example 2'
        incoming_port_maps: ["20000:22"]
        incoming_examples_port_maps: ["20002:22"]
        # outcomment the above defs to not expose any ports. Syntax is the one
        # used in the ansible dockr module (NOTE: as long as we use the
        # workaround, don't use commas but a list instead)
  vars:
      - image_storage_dir: docker_images
