---
- hosts: build
  roles:
      - { role: build_and_save_container, dockerfile_dir: '../',
        image_file_name: 'incoming', image_name: 'lars.tiede/incoming',
        image_tag: 'latest'}
  vars:
      - image_storage_dir: docker_images
