---
- name: kill and remove incoming, incoming_examples and incoming_example_webserver containers
  remote_user: root
  shell: docker kill {{ item }} && docker rm {{ item }}
  with_items:
      - incoming_example_webserver
      - incoming_examples
      - incoming
  failed_when: False
# TODO: this should be done only if we installed new images. How can we get
# that info over from the other role?
#- debug: var=hostvars[inventory_hostname]

- name: have incoming container running
  remote_user: root
  docker: image="lars.tiede/incoming" name="incoming" state="running"
      {% if incoming_port_maps is defined %} ports={{ incoming_port_maps }} {% endif %}
      tty=yes
  register: container_incoming
- set_fact:
    #incoming_ip: "{{ docker_containers|selectattr('Name', 'equalto', '/incoming')|first.NetworkSettings.IPAddress }}" # this should work but doesn't because my Ansible version doesn't know the 'equalto' Jinja2 test yet :(
    incoming_internal_ip: "{{ docker_containers[0].NetworkSettings.IPAddress }}"

- name: have web app example container running
  remote_user: root
  docker: image="lars.tiede/incoming_examples" name="incoming_examples" state="running"
      volumes_from="incoming"
      {% if incoming_examples_port_maps is defined %} ports={{ incoming_examples_port_maps }} {% endif %}
      env='PUBLIC_HOSTNAME={{ ansible_fqdn }},PUBLIC_INCOMING_HOSTNAME={{ ansible_fqdn }},INTERNAL_INCOMING_HOSTNAME={{ incoming_internal_ip }}:4000'
      tty=yes
      #' this just for buggy vim syntax highlight
  register: container_webapp
- set_fact:
    webapps_internal_ip: "{{ docker_containers[0].NetworkSettings.IPAddress }}"

# the following, for reference
#- debug: var=container_incoming.ansible_facts.docker_containers[0]
#- debug: var=container_webapp
#- debug: var=incoming_internal_ip
#- debug: var=webapps_internal_ip

- name: have directory for dockerized nginx sites-enabled files
  remote_user: root
  file: path=/root/docker_webserver_config/sites-enabled state=directory

- name: have directory for dockerized nginx logs
  remote_user: root
  file: path=/var/log/nginx-docker state=directory

- name: have nginx server config preamble
  remote_user: root
  template: src=sites-enabled/00_http_upgrade_magic dest=/root/docker_webserver_config/sites-enabled/00_http_upgrade_magic

- name: do we have an SSL cert for the target host?
  local_action: stat path="ssl-certs/{{ ansible_fqdn }}-nginx.pem"
  sudo: false
  register: stat_ssl_cert

- name: have directory for dockerized nginx cert files
  remote_user: root
  file: path=/root/docker_webserver_config/certs state=directory
  when: stat_ssl_cert.stat.exists

- name: have SSL cert and key
  remote_user: root
  copy: src=ssl-certs/{{ item }} dest=/root/docker_webserver_config/certs/{{ item }}
  with_items:
      - "{{ ansible_fqdn }}-nginx.pem"
      - "{{ ansible_fqdn }}.key"
  when: stat_ssl_cert.stat.exists

- name: have nginx server config for example app
  remote_user: root
  template: src=sites-enabled/example_apps dest=/root/docker_webserver_config/sites-enabled/example_app.conf

- name: have webserver container running
  remote_user: root
  docker: image="lars.tiede/incoming_example_webserver"
      name="incoming_example_webserver" state="running"
      volumes="/root/docker_webserver_config/sites-enabled:/etc/nginx/sites-enabled,/root/docker_webserver_config/certs:/etc/nginx/certs,/var/log/nginx-docker:/var/log/nginx"
      ports="{{ nginx_server_port }}:80,{{ nginx_ssl_server_port }}:443"
      tty=yes
  register: container_webserver
